import { CustomError } from './abstraction/custom.error';

export class AlreadyExistsError extends CustomError {
  constructor(message = 'JÃ¡ existe', statusCode = 409) {
    super(statusCode, message);
  }
}
